### PR TITLE
Add a license

### LINKED ISSUE #142: Provide licence

### PR DESCRIPTION
**Pull request by xeruf**
I recommend the GPLv3 for now, because it allows people to contribute but not use the code for closed source or commercial purposes. You can always switch to the more permissive MIT in the future.

See https://choosealicense.com/ for more information as well as the troubles incurred by not having one.

Fixes #142

### CODE REVIEW

**Comment by sghpjuikit** [comment]
Thx for the effort. I will look into this. Just be aware that dual licencing may be necessary.

**Comment by sghpjuikit** [comment]
I'm not sure GPL licence is the best for us - it allows commercial derivatives. It is also viral - I see no point forcing everyone to open-source their derivatives. What I'd like to have is literally free for anything but commercial use licence.

The problem is that vlcj is GPL (not with classpath exception), which forces us into GPL. We may be able to get a different licence if we ask or dual licence this - but I'm not sure.

1 Before providing a licence, we must check each classpath dependency and make sure that it does not force us into a specific licence.

2 Then we must check all at-runtime-loaded dependencies (which we do have for widgets...) and see if they do not force a specific licence onto us.

3 Then we must check if we do not  distribute any licenced software (vlc, etc).

**Comment by sghpjuikit** [comment]
In order to just start with something we could just use really restrictive licence and then allow more freedoms later, except we can't, since licences can force derivatives to use same licence. That's why this is taking me so long... Cant start with most free licence nor the most restrictive one. It need to be the right one from the start!

**Comment by sghpjuikit** [comment]
I'll be talking about this on Zulip

**Comment by Xerus2000** [comment]
> it allows commercial derivatives

Afaik only if the source code of the derivative is made available, which prevents any sort of abuse.

**Comment by sghpjuikit** [comment]
> Afaik only if the source code of the derivative is made available, which prevents any sort of abuse.

No, it always permits that. Although it forces disclosing the source code only when app is distributed (released) - the latter is ok for us, but the former is so so.

> This player is not some library

That is exactly why - library would be ok - not product. Making this free for commercial use actually may be dangerous. I do not think this will take over the world or even catch on, or even have its own niche, but its about the potential - using GPL will take our freedom away and make anyone able to just fork and do stuff and even keep pulling our work and keep selling it - that's unenviable situation. I'm not very comfortable with that, because I didnt pour 6 years of life into this so someone can effectively steal it to get money - repeatedly

I understand that you want to progress with the release, but this is a very important to get right. So I ask for patience.

**Comment by Xerus2000** [comment]
> using GPL will take our freedom away and make anyone able to just fork and do stuff and even keep pulling our work and keep selling it

I don't think that's what GPL accomplishes.

> The GNU GPLv3 also lets people do almost anything they want with your project, except to distribute closed source versions.

https://choosealicense.com/
People can commercialize it, yes, but not proprietarily, which protects your freedom.

> If you do distribute YOUR APPLICATION, and you used something GPL as part of your application (even if only linking at run-time to a library) - and even if you do not charge money - and even if you do not change that GPL s/w in any way - then you MUST make the source of YOUR APPLICATION available.

https://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application

**Comment by defvs** [comment]
Note that you can definitely create your own license. Example : http://dbad-license.org/
It's as simple as explicitely stating in a text file what you want and don't want. You can as well edit the GPL to your needs :)

**Comment by sghpjuikit** [comment]
@defvs The issue with custom licences is simple: they are not battle tested and thus, have high probability of not holding up against lawyers.

**Comment by defvs** [comment]
See this StackOverflow answer (first one), it explains a lot. https://softwareengineering.stackexchange.com/questions/171263/how-can-i-create-my-own-software-license

**Pull request closed without merging**
